import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.setDefaultTimeout(15000);
await p.goto('http://127.0.0.1:8899/list-your-tours/', { waitUntil: 'domcontentloaded' });
console.log('form count:', await p.locator('.operator-form').count());
await p.evaluate(() => document.querySelector('.operator-form')?.scrollIntoView());
await p.waitForTimeout(800);
await p.screenshot({ path: '/tmp/shots/op-form.png' });
await p.fill('#pt-op-company', 'Blue Horizon Charters');
await p.fill('#pt-op-contact', 'Test Contact');
await p.fill('#pt-op-email', 'ops@example.com');
await p.fill('#pt-op-phone', '+506 0000 0000');
await p.fill('#pt-op-location', 'Tamarindo');
await p.locator('.operator-form__check input').first().check();
await p.fill('#pt-op-tours', 'Inshore half day — 4 hours');
await p.selectOption('#pt-op-insured', 'yes');
await p.click('button[name="pt_operator_submit"]');
await p.waitForTimeout(1500);
console.log('URL:', p.url());
console.log('MSG:', (await p.locator('.operator-form').innerText()).slice(0,160).replace(/\n/g,' '));
await b.close();
