import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://127.0.0.1:8899/learn-to-surf-tamarindo-beginners-guide/', { waitUntil: 'networkidle' });
await p.screenshot({ path: '/tmp/shots/post-top.png' });
await p.locator('.post-answer').scrollIntoViewIfNeeded().catch(()=>{});
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/shots/post-answer.png' });
await p.locator('.wp-block-details').first().scrollIntoViewIfNeeded().catch(()=>{});
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/shots/post-faq.png' });
await b.close(); console.log('ok');
