// Executive Brief — the domain engine (Engine -> API -> UI). No React, no UI
// concerns, fully testable in isolation. This is NOT a new intelligence
// source: it aggregates the real engines that already exist — the Mission
// Queue (the single source of truth for work), the Agent Roster, the
// Activity Stream, and Mission Atlas's external-intelligence snapshot — into
// one normalized "read this first" briefing. Every sentence traces back to a
// real evidence reference; nothing is generated by an LLM, guessed, or
// forecast. Where a real data source isn't connected, that is stated
// honestly rather than papered over.

import type { Mission, MissionQueueSnapshot } from '../missions/engine'
import type { AgentRosterSnapshot } from '../agents/runtime'
import type { ActivityEvent } from '../types'
import type { AtlasSnapshot } from '../external/service'
import type { GscReport } from '../external/providers/search-console'

export type BriefEvidenceKind = 'mission' | 'agent' | 'metric' | 'activity'

export interface BriefEvidenceRef {
  kind: BriefEvidenceKind
  id: string
  label: string
}

export interface BriefItem {
  text: string
  why: string | null
  evidence: BriefEvidenceRef[]
}

export type AttentionSeverity = 'blocked' | 'pending-approval' | 'verification-failed' | 'canceled'

export interface AttentionItem extends BriefItem {
  severity: AttentionSeverity
}

export interface PerformanceMetric {
  label: string
  value: string
  deltaLabel: string | null
  source: string
}

export interface DataSourceStatus {
  name: string
  available: boolean
  reason: string | null
}

export interface ExecutiveBrief {
  generatedAt: string
  project: { id: string; name: string }
  executiveSummary: string
  priorities: BriefItem[]
  recentProgress: BriefItem[]
  attentionRequired: AttentionItem[]
  performance: { metrics: PerformanceMetric[]; note: string | null }
  recommendation: { text: string; reasoning: string; evidence: BriefEvidenceRef[] } | null
  dataSources: DataSourceStatus[]
}

const SEVERITY_RANK: Record<Mission['severity'], number> = { critical: 3, warning: 2, info: 1 }

function missionRef(m: Mission): BriefEvidenceRef {
  return { kind: 'mission', id: m.id, label: m.title }
}

function actionableMissions(queue: MissionQueueSnapshot): Mission[] {
  return queue.missions.filter((m) => m.stage !== 'completed' && m.stage !== 'failed')
}

// Highest-value real actions: waiting-for-approval and retry missions,
// ranked by severity then confidence — never padded with invented work.
function priorityMissions(queue: MissionQueueSnapshot): Mission[] {
  return actionableMissions(queue)
    .filter((m) => m.stage === 'waiting-for-approval' || m.stage === 'retry')
    .sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity] || b.confidence - a.confidence)
}

function buildPriorities(queue: MissionQueueSnapshot): BriefItem[] {
  return priorityMissions(queue)
    .slice(0, 5)
    .map((m) => ({
      text: m.stage === 'retry' ? `Review "${m.title}" — it needs another look.` : `Approve "${m.title}".`,
      why: m.blockingReason ?? `${m.severity} severity, ${m.confidence}% confidence — ready to act on.`,
      evidence: [missionRef(m)],
    }))
}

const PROGRESS_EVENT_TYPES = new Set([
  'verification.passed',
  'recommendation.generated',
  'scout.discovery_completed',
  'approval.granted',
])

function buildRecentProgress(events: ActivityEvent[]): BriefItem[] {
  return events
    .filter((e) => PROGRESS_EVENT_TYPES.has(e.type))
    .slice(0, 8)
    .map((e) => ({
      text: e.summary,
      why: null,
      evidence: (
        [
          e.missionId ? { kind: 'mission', id: e.missionId, label: e.summary } : null,
          e.agentRole ? { kind: 'agent', id: e.agentRole, label: e.agentRole } : null,
        ] as (BriefEvidenceRef | null)[]
      ).filter((x): x is BriefEvidenceRef => x !== null),
    }))
}

function buildAttentionRequired(queue: MissionQueueSnapshot, events: ActivityEvent[]): AttentionItem[] {
  const items: AttentionItem[] = []
  for (const m of queue.missions) {
    if (m.stage === 'retry') {
      items.push({ text: `"${m.title}" is blocked.`, why: m.blockingReason, severity: 'blocked', evidence: [missionRef(m)] })
    } else if (m.stage === 'waiting-for-approval') {
      items.push({ text: `"${m.title}" is waiting for your approval.`, why: null, severity: 'pending-approval', evidence: [missionRef(m)] })
    } else if (m.stage === 'failed') {
      items.push({ text: `"${m.title}" was canceled.`, why: m.blockingReason, severity: 'canceled', evidence: [missionRef(m)] })
    }
  }
  for (const e of events) {
    if (e.type === 'verification.failed') {
      items.push({
        text: e.summary,
        why: e.detail,
        severity: 'verification-failed',
        evidence: e.missionId ? [{ kind: 'mission', id: e.missionId, label: e.summary }] : [],
      })
    }
  }
  return items
}

// A meaningful move, not noise — mirrors the threshold already used for
// Mission Atlas's own significant-change detection (see change-detection.ts).
const MEANINGFUL_DELTA_RATIO = 0.05

function gscMetrics(current: AtlasSnapshot['gsc'], prior: GscReport | null): PerformanceMetric[] {
  if (current.evidence.grade === 'unavailable' || !current.value) return []
  const rows = current.value.rows
  const clicks = rows.reduce((n, r) => n + r.clicks, 0)
  const impressions = rows.reduce((n, r) => n + r.impressions, 0)
  const metrics: PerformanceMetric[] = []
  let clicksDelta: string | null = null
  if (prior) {
    const priorClicks = prior.rows.reduce((n, r) => n + r.clicks, 0)
    if (priorClicks > 0 && Math.abs(clicks - priorClicks) / priorClicks >= MEANINGFUL_DELTA_RATIO) {
      const pct = Math.round(((clicks - priorClicks) / priorClicks) * 100)
      clicksDelta = `${pct > 0 ? '+' : ''}${pct}% vs prior period`
    }
  }
  metrics.push({ label: 'Search Console clicks', value: String(clicks), deltaLabel: clicksDelta, source: 'Search Console' })
  metrics.push({ label: 'Search Console impressions', value: String(impressions), deltaLabel: null, source: 'Search Console' })
  return metrics
}

function ga4Metrics(current: AtlasSnapshot['analytics']): PerformanceMetric[] {
  if (current.evidence.grade === 'unavailable' || !current.value) return []
  const sessions = current.value.pages.reduce((n, p) => n + p.sessions, 0)
  const conversions = current.value.pages.reduce((n, p) => n + p.conversions, 0)
  return [
    { label: 'Analytics sessions', value: String(sessions), deltaLabel: null, source: 'Analytics (GA4)' },
    { label: 'Analytics conversions', value: String(conversions), deltaLabel: null, source: 'Analytics (GA4)' },
  ]
}

function buildPerformance(atlas: AtlasSnapshot | null, priorGsc: GscReport | null): ExecutiveBrief['performance'] {
  if (!atlas) return { metrics: [], note: 'External intelligence is unavailable right now.' }
  const changeMetrics: PerformanceMetric[] = atlas.changes
    .filter((c) => c.significant)
    .map((c) => ({
      label: c.subject,
      value: String(c.after ?? '—'),
      deltaLabel: `${c.delta > 0 ? '+' : ''}${c.delta}`,
      source: c.category,
    }))
  const metrics = [...gscMetrics(atlas.gsc, priorGsc), ...ga4Metrics(atlas.analytics), ...changeMetrics]
  return {
    metrics,
    note: metrics.length === 0 ? 'No meaningful metric movement to report — connect Search Console or Analytics for deeper insight.' : null,
  }
}

function buildDataSources(atlas: AtlasSnapshot | null): DataSourceStatus[] {
  const of = (name: string, obs: { evidence: { grade: string; note?: string } } | undefined): DataSourceStatus => ({
    name,
    available: obs ? obs.evidence.grade !== 'unavailable' : false,
    reason: obs && obs.evidence.grade === 'unavailable' ? (obs.evidence.note ?? 'Not connected.') : null,
  })
  return [
    { name: 'Mission Queue', available: true, reason: null },
    { name: 'Agent Roster', available: true, reason: null },
    { name: 'Activity Stream', available: true, reason: null },
    of('Search Console', atlas?.gsc),
    of('Analytics (GA4)', atlas?.analytics),
    of('Backlinks', atlas?.backlinks),
    of('AI Visibility', atlas?.aiVisibility),
    { name: 'Notifications', available: false, reason: 'Not built yet.' },
  ]
}

function buildExecutiveSummary(
  project: { name: string },
  queue: MissionQueueSnapshot,
  roster: AgentRosterSnapshot,
  events: ActivityEvent[]
): string {
  const s = queue.summary
  const activeAgents = roster.agents.filter((a) => a.status === 'active' || a.status === 'verifying')
  if (s.total === 0) {
    return `${project.name} has no missions yet. Run a scan to give Scout something to find.`
  }
  const parts: string[] = []
  parts.push(`${project.name} has ${s.total} mission${s.total === 1 ? '' : 's'} tracked`)
  const clauses: string[] = []
  if (s.waitingForApproval > 0) clauses.push(`${s.waitingForApproval} awaiting your approval`)
  if (s.active > 0) clauses.push(`${s.active} actively in flight`)
  if (s.retry > 0) clauses.push(`${s.retry} needing another look`)
  if (s.completed > 0) clauses.push(`${s.completed} completed`)
  if (clauses.length) parts.push(`: ${clauses.join(', ')}`)
  parts.push('.')
  if (activeAgents.length > 0) {
    parts.push(` ${activeAgents.map((a) => a.name).join(' and ')} ${activeAgents.length === 1 ? 'is' : 'are'} working right now.`)
  }
  if (events.length > 0) {
    parts.push(` ${events.length} event${events.length === 1 ? '' : 's'} in the last 24 hours.`)
  }
  return parts.join('')
}

function buildRecommendation(
  queue: MissionQueueSnapshot,
  priorities: Mission[],
  atlasRecommendation: string | null
): ExecutiveBrief['recommendation'] {
  const top = priorities[0]
  if (top) {
    return {
      text: top.stage === 'retry' ? `Review "${top.title}" before anything else.` : `Approve "${top.title}" next.`,
      reasoning: `Of ${queue.summary.total} tracked mission${queue.summary.total === 1 ? '' : 's'}, this is the highest-severity item awaiting a decision (${top.severity} severity, ${top.confidence}% confidence).`,
      evidence: [missionRef(top)],
    }
  }
  if (atlasRecommendation) {
    return { text: atlasRecommendation, reasoning: 'Based on external intelligence (rankings, backlinks, AI-search visibility).', evidence: [] }
  }
  return null
}

export function buildExecutiveBrief(input: {
  project: { id: string; name: string }
  missionQueue: MissionQueueSnapshot
  roster: AgentRosterSnapshot
  recentActivity: ActivityEvent[]
  atlas: AtlasSnapshot | null
  priorGsc: GscReport | null
  now: string
}): ExecutiveBrief {
  const { project, missionQueue, roster, recentActivity, atlas, priorGsc, now } = input
  const priorities = priorityMissions(missionQueue)

  return {
    generatedAt: now,
    project,
    executiveSummary: buildExecutiveSummary(project, missionQueue, roster, recentActivity),
    priorities: buildPriorities(missionQueue),
    recentProgress: buildRecentProgress(recentActivity),
    attentionRequired: buildAttentionRequired(missionQueue, recentActivity),
    performance: buildPerformance(atlas, priorGsc),
    recommendation: buildRecommendation(missionQueue, priorities, atlas ? atlas.briefing.recommendedMission : null),
    dataSources: buildDataSources(atlas),
  }
}
