<?php get_header(); ?>
<main id="main">

<section class="page-hero">
  <img class="page-hero-bg" src="https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&amp;fit=crop&amp;w=1920&amp;q=72" srcset="https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&amp;fit=crop&amp;w=768&amp;q=72 768w, https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&amp;fit=crop&amp;w=1280&amp;q=72 1280w, https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&amp;fit=crop&amp;w=1920&amp;q=72 1920w, https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&amp;fit=crop&amp;w=2560&amp;q=72 2560w" sizes="100vw" alt="Team working late in a glass-walled meeting room" loading="eager" fetchpriority="high">
  <div class="wrap">
    <nav class="breadcrumb" aria-label="Breadcrumb">
      <a href="<?php echo esc_url(home_url("/")); ?>">Home</a> /
      <a href="<?php echo esc_url(home_url("/cookie-policy/")); ?>">Cookie Policy</a>
    </nav>
    <span class="eyebrow eyebrow--light">Legal</span>
    <h1>Cookie Policy</h1>
    <p>How EnVue Telematics uses cookies on this website.</p>
    <div class="hero-actions">
      <a class="button button-primary button-lg" href="<?php echo esc_url(home_url("/privacy-policy/")); ?>">Privacy Policy <span>&rarr;</span></a>
      <a class="button button-ghost button-lg" href="<?php echo esc_url(home_url("/get-in-touch/")); ?>">Contact Us</a>
    </div>
  </div>
</section>

<style>
.legal-prose{max-width:75ch;margin:0 auto;color:var(--slate);}
.legal-prose h2{font-size:clamp(22px,2.2vw,28px);color:var(--ink);margin:2.25rem 0 .85rem;}
.legal-prose h3{font-size:1.15rem;color:var(--ink);margin:1.75rem 0 .6rem;}
.legal-prose p{font-size:16px;line-height:1.8;margin:0 0 1.1rem;}
.legal-prose ul{list-style:disc;padding-left:1.5rem;margin:0 0 1.25rem;display:flex;flex-direction:column;gap:.5rem;}
.legal-prose li{line-height:1.7;}
.legal-prose a{color:var(--brand);text-decoration:underline;}
.legal-prose table{width:100%;border-collapse:collapse;margin:1.5rem 0;font-size:14.5px;}
.legal-prose th,.legal-prose td{border:1px solid var(--line);padding:10px 12px;text-align:left;vertical-align:top;}
.legal-prose th{background:var(--bg-soft);color:var(--ink);}
.legal-prose .legal-table-wrap{overflow-x:auto;}
</style>

<section class="section"><div class="wrap">
  <div class="legal-prose">
    <p>This page provides comprehensive information about how we use cookies on our website to enhance your browsing experience, improve website performance, and deliver personalized content. Cookies are small text files that are stored on your device when you visit our site. They help us understand how visitors interact with our website, allowing us to offer a smoother and more efficient user experience. In the table below, you will find detailed information about each type of cookie we use, their purpose, and how long they remain on your device. We are committed to respecting your privacy and providing transparency about the data we collect through cookies. For more information on how we handle your personal data, please see our <a href="<?php echo esc_url(home_url("/privacy-policy/")); ?>">Privacy Policy.</a></p>

    <?php
    // Cookie table is generated by the WPConsent plugin.
    if ( shortcode_exists( 'wpconsent_cookie_policy' ) ) {
        echo '<div class="legal-table-wrap">' . do_shortcode( '[wpconsent_cookie_policy]' ) . '</div>';
    }
    ?>
  </div>
</div></section>

</main>
<section class="final-cta" id="demo"><div class="wrap final-grid">
  <div>
    <span class="eyebrow eyebrow--light">Questions?</span>
    <h2>We&rsquo;re here to help.</h2>
  </div>
  <div>
    <p>Questions about cookies or your data? Contact EnVue Telematics at support@et-envue.com or call (800) 201-1169.</p>
    <div class="hero-actions">
      <a class="button button-primary button-lg" href="<?php echo esc_url(home_url("/get-in-touch/")); ?>">Contact Us <span>&rarr;</span></a>
      <a class="button button-ghost button-lg" href="tel:8002011169">Call (800) 201-1169</a>
    </div>
  </div>
</div></section>
<?php get_footer(); ?>
