const all=require('./results.json'); const R=all.filter(r=>r.ok); const n=R.length;
const med=a=>{a=[...a].sort((x,y)=>x-y);const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2};
const pct=k=>`${k}/${n} (${Math.round(100*k/n)}%)`;
const cnt=f=>R.filter(f).length;
const tally=(get)=>{const o={};R.forEach(r=>[].concat(get(r)||[]).forEach(k=>o[k]=(o[k]||0)+1));return Object.entries(o).sort((a,b)=>b[1]-a[1])};
const S={};
S.candidates=all.length; S.ok=n; S.blocked=all.filter(r=>!r.ok).map(r=>r.domain+': '+r.failure);
S.platform=tally(r=>r.platform); S.wp_builder=tally(r=>r.wp_builder||[]); S.hosting=tally(r=>r.hosting);
S.vendor=tally(r=>r.vendor||'(none credited)');
S.median_bytes=med(R.map(r=>r.bytes)); S.p25_bytes=0; S.max_bytes=Math.max(...R.map(r=>r.bytes)); S.min_bytes=Math.min(...R.map(r=>r.bytes));
S.median_scripts=med(R.map(r=>r.script_tags)); S.median_ext_scripts=med(R.map(r=>r.external_scripts)); S.median_3p_hosts=med(R.map(r=>r.third_party_script_host_count)); S.median_3p_hosts_incl_inline=med(R.map(r=>r.third_party_hosts_incl_inline)); S.max_3p_incl=Math.max(...R.map(r=>r.third_party_hosts_incl_inline)); S.median_inline_scripts=med(R.map(r=>r.inline_scripts)); S.sites_ge_5_3p=pct(cnt(r=>r.third_party_hosts_incl_inline>=5));
S.sites_ge_50_scripts=pct(cnt(r=>r.script_tags>=50)); S.sites_ge_10_3p=pct(cnt(r=>r.third_party_script_host_count>=10));
S.median_ttfb=med(R.map(r=>r.ttfb_s)); S.median_total=med(R.map(r=>r.total_s));
S.top_3p_hosts=tally(r=>r.third_party_script_hosts).slice(0,15);
S.chat_any=pct(cnt(r=>Object.keys(r.chat_widgets).length)); S.chat=tally(r=>Object.keys(r.chat_widgets));
S.call_any=pct(cnt(r=>Object.keys(r.call_tracking).length)); S.call=tally(r=>Object.keys(r.call_tracking));
S.analytics=tally(r=>Object.keys(r.analytics)); S.no_analytics=pct(cnt(r=>!Object.keys(r.analytics).length));
S.jsonld_any=pct(cnt(r=>r.jsonld_blocks>0)); S.jsonld_parse_err_sites=cnt(r=>r.jsonld_parse_errors>0);
for(const k of ['LegalService','Attorney','LocalBusiness','Organization','FAQPage','Review_or_AggregateRating','BreadcrumbList','WebSite','Person','any_legal_business']) S['schema_'+k]=pct(cnt(r=>r.schema[k]));
S.no_legal_schema=pct(cnt(r=>!r.schema.any_legal_business));
S.schema_types_top=tally(r=>r.schema_types).slice(0,20);
S.contact_form=pct(cnt(r=>r.contact_form)); S.form_iframe_only=cnt(r=>!r.contact_form&&r.form_iframe.length);
S.no_static_form_but_js_form_embed=pct(cnt(r=>!r.contact_form&&r.js_form_embeds.length)); S.no_form_signal_at_all=pct(cnt(r=>!r.contact_form&&!r.js_form_embeds.length&&!Object.keys(r.chat_widgets).length)); S.tel=pct(cnt(r=>r.tel_links>0)); S.meta_desc=pct(cnt(r=>r.meta_description)); S.meta_desc_over160=cnt(r=>r.meta_description_len>160);
S.h1_exactly1=pct(cnt(r=>r.h1_count===1)); S.h1_none=pct(cnt(r=>r.h1_count===0)); S.h1_multi=pct(cnt(r=>r.h1_count>1));
S.viewport=pct(cnt(r=>r.viewport));
S.median_imgs=med(R.map(r=>r.img_count)); S.sites_missing_alt=pct(cnt(r=>r.img_missing_alt>0));
const ti=R.reduce((a,r)=>a+r.img_count,0), tm=R.reduce((a,r)=>a+r.img_missing_alt,0), te=R.reduce((a,r)=>a+r.img_empty_alt,0);
S.imgs_total=ti; S.imgs_missing_alt=tm; S.imgs_empty_alt=te;
S.reviews=pct(cnt(r=>r.mentions_reviews));
S.no_form_no_chat=pct(cnt(r=>!r.contact_form&&!Object.keys(r.chat_widgets).length));
// platform x vendor
S.vendor_by_platform=tally(r=>r.vendor?r.platform+' / '+r.vendor:[]);
console.log(JSON.stringify(S,null,1));
fs=require('fs');fs.writeFileSync('stats.json',JSON.stringify(S,null,1));
