// "Websites for <trade>" landing pages: local trades, health, food and retail.
// Every claim here must match what SaySites actually does today (see
// app/page.tsx, lib/starter.ts and lib/visibility.ts). No booking, ordering,
// call tracking or ranking promises.

import type { Industry } from './types'

export const TRADES: Industry[] = [
  // ---------------------------------------------------------------- Plumbers
  {
    slug: 'plumbers',
    type: 'plumber',
    example: 'rivertown-plumbing',
    plural: 'plumbers',
    title: 'Websites for Plumbers | SaySites',
    description: 'A fast plumbing website set up for Google: a page per service, your service area, a big call button and a contact form. Built for you, $15 a month.',
    kicker: 'Websites for plumbers',
    h1: 'A plumbing website that answers the emergency call',
    lede: 'When a pipe bursts, people search on their phone and call the first plumber who looks local and trustworthy. SaySites builds a fast site that puts your number, your towns and your services in front of them.',
    problems: [
      { title: 'Emergency searches are won in seconds', body: 'Someone standing in an inch of water will not wait for a slow page to load or hunt for a phone number. If your site is slow or your number is buried, they go back and call the next result.' },
      { title: 'One page trying to cover every job', body: 'Drain cleaning, water heaters, leak repair and repiping are different searches. A single Services page listing them all gives Google very little to rank for any one of them.' },
      { title: 'Google is not sure where you work', body: 'Without a clear address, phone number and list of the towns you cover, your site is hard to connect with searches made across your service area.' },
      { title: 'No time to maintain a website', body: 'You are on jobs all day. Updating hours, adding a new service or posting a seasonal tip slips to the bottom of the list, and the site goes stale.' },
    ],
    pages: [
      { name: 'Home', why: 'Your phone number and a call button at the top, the towns you serve, and your main services, so an emergency caller can act in one tap.' },
      { name: 'Services', why: 'An overview of everything you do, linking to a page for each main service.' },
      { name: 'A page per service', why: 'Water heaters, drain cleaning, leak detection and so on each get their own page, so each can rank for the people searching for it.' },
      { name: 'Service area', why: 'A plain list of the towns and neighborhoods you cover, written for people, which helps Google match you to searches across your area.' },
      { name: 'Contact', why: 'Phone, hours and a contact form for non-urgent jobs. Messages land in your SaySites inbox with reply and call buttons.' },
      { name: 'Blog', why: 'Short, useful posts, such as how to shut off your water main, that answer questions homeowners search for.' },
    ],
    searches: [
      'emergency plumber near me',
      'plumber [your city]',
      'water heater repair near me',
      'blocked drain [your city]',
      'leaking pipe under sink repair',
      '24 hour plumber near me',
    ],
    seo: [
      { title: 'Marked up as a Plumber', body: 'Your site tells search engines, in structured data, that you are a Plumber, with your address, phone number and opening hours. That is the information Google uses for local results.' },
      { title: 'One page for each service', body: 'Each main service gets its own page with its own title and heading, so "water heater repair [your city]" can land on a page that is actually about water heaters.' },
      { title: 'Fast on a phone', body: 'Every page must pass a 95+ speed check before it goes live. Emergency searches happen on phones, often on a weak signal, and speed is part of how Google ranks pages.' },
      { title: 'Honest local details, no tricks', body: 'We write one genuine service-area page instead of dozens of near-identical town pages. Google treats those copies as spam, and they rarely help.' },
    ],
    sofie: [
      'Add a page about tankless water heaters',
      'Add Maplewood and Cedar Falls to the towns we serve',
      'Change our hours to include Saturday mornings',
      'Write a blog post on how to stop a frozen pipe from bursting',
      'Put our emergency phone number in bigger type on the home page',
    ],
    faq: [
      { q: 'How much does a plumbing website cost?', a: 'SaySites is $15 a month after a 7-day free trial, which covers the site, hosting, your own domain, speed checks and changes made by Sofie. There are no setup fees and you can cancel anytime.' },
      { q: 'Do I need to be technical to run it?', a: 'No. You describe your business and SaySites builds the site. After that you ask Sofie for changes in plain words, like adding a service or changing your hours. You see each change as a draft first and can undo it.' },
      { q: 'Will I show up for emergency plumber searches?', a: 'Nobody can honestly promise a ranking. What SaySites does is get the foundations right: a fast site, a Plumber business type with your address, phone and hours, a page per service and a clear service area. Pair that with a complete Google Business Profile and real reviews and you give yourself a fair chance.' },
      { q: 'Can I list every town I cover?', a: 'Yes. Your service-area page can name every town and neighborhood you work in. We keep it to one honest page rather than a stack of copied town pages, because Google treats those as spam.' },
      { q: 'Can customers book a job online?', a: 'There is no online booking system. Customers can tap to call you or send a message through your contact form, which lands in your inbox with reply and call buttons.' },
      { q: 'Can I use my own domain?', a: 'Yes. Every site gets a free yourname.saysites.com address, and you can connect a domain you already own.' },
    ],
  },

  // ------------------------------------------------------------ Electricians
  {
    slug: 'electricians',
    type: 'electrician',
    example: 'northside-electric',
    plural: 'electricians',
    title: 'Websites for Electricians | SaySites',
    description: 'A fast electrician website with a page per service, your license details, the towns you cover and a contact form, set up for local search. $15 a month.',
    kicker: 'Websites for electricians',
    h1: 'An electrician website that earns trust before the call',
    lede: 'People hiring an electrician want to know you are licensed, local and careful. SaySites builds a fast site that shows it, and gives each of your services a page Google can find.',
    problems: [
      { title: 'Trust has to be visible', body: 'Electrical work is a safety job. Homeowners look for a license number, insurance, real photos and real reviews before they call, and a thin site gives them none of it.' },
      { title: 'Big jobs and small jobs look the same', body: 'A panel upgrade, an EV charger install and a flickering light are very different searches. Lumped together on one page, none of them ranks well.' },
      { title: 'Commercial and residential in one place', body: 'If you do both, customers need to see quickly that you handle their kind of job. A muddled site loses both.' },
      { title: 'The site never changes', body: 'New services like EV chargers and home batteries appear, but updating the website keeps getting pushed back.' },
    ],
    pages: [
      { name: 'Home', why: 'Who you are, where you work, your license details and a call button, so a careful homeowner has what they need at a glance.' },
      { name: 'A page per service', why: 'Panel upgrades, EV charger installation, rewiring, lighting and fault finding each get a page that can rank on its own.' },
      { name: 'Residential and commercial', why: 'If you serve both, separate sections or pages make it clear to each customer that you do their kind of work.' },
      { name: 'Gallery', why: 'Photos of tidy panels and finished installs, uploaded from your phone and resized automatically, show the standard of your work.' },
      { name: 'Service area', why: 'The towns you cover, listed plainly on one page.' },
      { name: 'Contact', why: 'Phone, hours and a contact form for quotes. Messages land in your inbox.' },
    ],
    searches: [
      'electrician near me',
      'EV charger installation [your city]',
      'electrical panel upgrade near me',
      'emergency electrician near me',
      'licensed electrician [your city]',
      'outlet not working electrician',
    ],
    seo: [
      { title: 'Marked up as an Electrician', body: 'Structured data tells search engines you are an Electrician, with your address, phone and hours, which feeds the local results people see first.' },
      { title: 'Service pages with titles that fit', body: 'Each service page gets a title sized to show in full on Google and a single clear heading, such as "EV Charger Installation in [your city]".' },
      { title: 'Helpful posts on new work', body: 'Posts on questions like whether your panel can handle an EV charger answer real searches and show Google the site is active.' },
      { title: 'Speed and clean code', body: 'Every page passes a 95+ speed check before it goes live, and the site is plain, lean HTML that search engines read easily.' },
    ],
    sofie: [
      'Add a page about EV charger installation',
      'Add our license number to the footer',
      'Add a gallery with these photos of panel upgrades',
      'Write a blog post on signs your electrical panel needs replacing',
      'Split our services into residential and commercial sections',
    ],
    faq: [
      { q: 'What does it cost?', a: 'A 7-day free trial, then $15 a month for your full site, hosting, your own domain, speed checks and changes by Sofie. No setup fees, and you can cancel anytime.' },
      { q: 'I am not good with computers. Is that a problem?', a: 'Not at all. SaySites builds the site from a short description, and afterwards you ask Sofie for changes in plain words. Every change shows up as a draft you can check, and anything can be undone.' },
      { q: 'Can I show my license and insurance?', a: 'Yes. Ask Sofie to add your license number and insurance details to the footer, home page or an About page. Only include details that are current and accurate.' },
      { q: 'Can I show customer reviews?', a: 'Yes, in a testimonials section. Use real reviews from real customers, with their permission. SaySites will not invent reviews, and Google penalizes sites that do.' },
      { q: 'Will a page for EV chargers help?', a: 'A dedicated page is the best way to be relevant to searches for that service. It will not guarantee a ranking, but a clear, useful page on a fast site is what Google looks for.' },
      { q: 'How do I see if people are visiting?', a: 'Your dashboard shows page views per day and your most-read pages, counted without cookies, so there is no cookie banner on your site.' },
    ],
  },

  // ---------------------------------------------------------- HVAC companies
  {
    slug: 'hvac-companies',
    type: 'hvac',
    example: 'summit-heating-air',
    plural: 'HVAC companies',
    title: 'Websites for HVAC Companies | SaySites',
    description: 'A fast heating and air website with a page for each service, seasonal posts, your service area and a contact form, set up for local search. $15 a month.',
    kicker: 'Websites for HVAC companies',
    h1: 'A heating and air website ready for every season',
    lede: 'HVAC searches rise with the first cold snap and the first heat wave. SaySites builds a fast site with a page for every service, so you are ready when people start looking.',
    problems: [
      { title: 'Demand arrives all at once', body: 'The day the furnace quits in January or the AC dies in July, people search and call within minutes. A slow or confusing site loses those calls to whoever loads first.' },
      { title: 'Repair, install and maintenance are separate searches', body: 'Someone pricing a new heat pump searches differently from someone whose furnace is making a noise. One general page does not serve either.' },
      { title: 'Maintenance plans are hard to explain', body: 'Tune-up plans keep the calendar full in slow months, but they need a clear page that explains what is included.' },
      { title: 'Seasonal content never gets written', body: 'You know what people should do before winter. Getting it onto the website while you are busiest is another matter.' },
    ],
    pages: [
      { name: 'Home', why: 'Heating and cooling at a glance, the towns you cover and a call button at the top for no-heat and no-cool emergencies.' },
      { name: 'Heating and cooling service pages', why: 'Furnace repair, AC repair, heat pumps, installs and duct work each get a page aimed at the people searching for it.' },
      { name: 'Maintenance plans', why: 'A page that explains what a tune-up plan includes and how to sign up through your contact form.' },
      { name: 'Service area', why: 'One clear page naming the towns you work in.' },
      { name: 'Blog', why: 'Seasonal posts, like getting your furnace ready for winter, that answer questions right when people ask them.' },
      { name: 'Contact', why: 'Phone, hours and a form for quotes and maintenance requests. Messages land in your inbox.' },
    ],
    searches: [
      'AC repair near me',
      'furnace not turning on',
      'heat pump installation [your city]',
      'HVAC company near me',
      'furnace tune up [your city]',
      'emergency AC repair near me',
    ],
    seo: [
      { title: 'Marked up as an HVAC business', body: 'Your structured data uses the HVACBusiness type with your address, phone and opening hours, the details Google relies on for local results.' },
      { title: 'Heating and cooling pages kept apart', body: 'Furnace, AC and heat pump pages each have their own title and heading, so each can match the searches made for it rather than competing with each other.' },
      { title: 'Posts that follow the seasons', body: 'Sofie can draft a fall heating checklist or a spring AC post. Fresh, useful posts answer real questions and show the business is active.' },
      { title: 'Fast when the weather turns', body: 'Every page passes a 95+ speed check before it goes live, so the site stays quick on a phone when people need you most.' },
    ],
    sofie: [
      'Add a page about heat pump installation',
      'Write a blog post on getting your furnace ready for winter',
      'Add a maintenance plan page with what the fall and spring tune-ups include',
      'Put a banner on the home page for our summer AC checkups',
      'Add ductless mini splits to our services',
    ],
    faq: [
      { q: 'How much is it?', a: 'SaySites is $15 a month after a 7-day free trial, for the full site, including hosting, your own domain, speed checks and changes by Sofie. No setup fees.' },
      { q: 'Do I need a web person to keep it updated?', a: 'No. You ask Sofie in plain words, like adding a seasonal banner or a new service. You see the change as a draft first and can undo it.' },
      { q: 'Can I take maintenance plan sign-ups?', a: 'You can have a page explaining your plans, and customers can ask to sign up through your contact form or by calling. There is no online payment for service plans on the Site plan.' },
      { q: 'Should I write seasonal blog posts?', a: 'They help. A short post answering a question people ask each fall or spring is useful to customers and shows Google the site is kept up. Sofie can draft them for you to check.' },
      { q: 'Can I show financing or rebate information?', a: 'Yes, as long as it is accurate. Ask Sofie to add a section with the details you give her. Keep it current, since outdated offers erode trust.' },
      { q: 'What is the Visibility Score?', a: 'A score from 0 to 100 showing how findable your site is, with step-by-step opportunities to improve it, such as adding your hours or giving each service its own page.' },
    ],
  },

  // ------------------------------------------------------------------ Roofers
  {
    slug: 'roofers',
    type: 'roofer',
    example: 'ridgeline-roofing',
    plural: 'roofers',
    title: 'Websites for Roofers | SaySites',
    description: 'A fast roofing website with photos of your work, a page per service, your service area and a contact form for estimates, set up for local search. $15/month.',
    kicker: 'Websites for roofers',
    h1: 'A roofing website that shows your work',
    lede: 'A roof is a big decision, and homeowners want to see real jobs before they ask for an estimate. SaySites builds a fast site with your photos, your services and a simple way to reach you.',
    problems: [
      { title: 'Homeowners compare several roofers', body: 'Few people hire the first roofer they find. They look at photos, read reviews and compare sites, and a thin site drops you out of the running.' },
      { title: 'Storm damage brings a rush', body: 'After a storm, people search for leak and storm repair right away. A slow site or a missing phone number sends them elsewhere.' },
      { title: 'Repairs and replacements need different pages', body: 'Someone with one missing shingle and someone planning a full replacement want different information. One page serves neither well.' },
      { title: 'Great work with no photos online', body: 'You have finished roofs on your phone, but getting them onto the website feels like a chore, so the site shows stock photos instead.' },
    ],
    pages: [
      { name: 'Home', why: 'Your towns, your services, a few photos of real roofs and a clear way to call or ask for an estimate.' },
      { name: 'A page per service', why: 'Roof replacement, roof repair, storm damage, gutters and flat roofs each get a page that can rank for its own searches.' },
      { name: 'Gallery', why: 'Before and after photos from your phone, resized automatically so the site stays fast.' },
      { name: 'Testimonials', why: 'Real reviews from homeowners, shown in their own section, to help people choose you.' },
      { name: 'Service area', why: 'One honest page listing the towns you cover.' },
      { name: 'Contact', why: 'A form for estimate requests that lands in your inbox, plus your phone and hours.' },
    ],
    searches: [
      'roof repair [your city]',
      'roofers near me',
      'roof leak repair near me',
      'storm damage roof repair',
      'roof replacement cost [your city]',
      'metal roofing contractor near me',
    ],
    seo: [
      { title: 'Marked up as a Roofing Contractor', body: 'Structured data describes you as a RoofingContractor with your address, phone and hours, which is what Google uses for local results.' },
      { title: 'A page for each kind of job', body: 'Replacement, repair and storm damage pages each carry their own title and heading, so they can match the searches people actually type.' },
      { title: 'Real photos, properly sized', body: 'Your own photos are resized automatically and every page passes a 95+ speed check, so a full gallery does not slow the site down.' },
      { title: 'Answers to cost questions', body: 'A helpful post on what affects the cost of a new roof answers a question homeowners search often, without promising prices you cannot keep.' },
    ],
    sofie: [
      'Add a gallery with these photos of last month’s roof replacements',
      'Add a page about storm damage repair',
      'Write a blog post on how to tell if your roof needs replacing',
      'Add these three customer reviews to the home page',
      'Change the main button to Request a free estimate',
    ],
    faq: [
      { q: 'What does a roofing website cost with SaySites?', a: '$15 a month after a 7-day free trial, covering the site, hosting, your own domain, speed checks and changes by Sofie. Cancel anytime.' },
      { q: 'Do I have to know how to build websites?', a: 'No. SaySites builds the site from a short description of your business. After that you ask Sofie for changes in plain words and check each one as a draft before it goes live.' },
      { q: 'Can I upload photos straight from my phone?', a: 'Yes. Upload them and they are resized for speed automatically. Real photos of your own roofs build more trust than stock images.' },
      { q: 'Can people request an estimate?', a: 'Yes, through your contact form. Requests land in your SaySites inbox with reply and call buttons. There is no scheduling or quoting system built in.' },
      { q: 'Should I make a page for every town after a storm?', a: 'No. Near-identical town pages are treated as spam by Google. One clear service-area page and a genuine storm damage page are the honest way to be found.' },
      { q: 'Can I show reviews from Google?', a: 'You can add real reviews to a testimonials section by giving them to Sofie. They are not pulled in automatically, and they should come from real customers.' },
    ],
  },

  // ------------------------------------------------------------- Landscapers
  {
    slug: 'landscapers',
    type: 'landscaper',
    example: 'green-acre-landscapes',
    plural: 'landscapers',
    title: 'Websites for Landscapers | SaySites',
    description: 'A fast landscaping website with a gallery of your yards, a page per service, your service area and a contact form for quotes, set up for local search.',
    kicker: 'Websites for landscapers',
    h1: 'A landscaping website that lets your yards do the talking',
    lede: 'Landscaping is sold on photos. SaySites builds a fast site with a gallery of your real work, a page for each service and a simple way to ask for a quote.',
    problems: [
      { title: 'Your best work is stuck on your phone', body: 'Customers want to see yards like theirs before they call. Without a gallery, your site asks them to take your word for it.' },
      { title: 'Design, maintenance and hardscaping are different buyers', body: 'Someone wanting weekly mowing and someone planning a patio search differently and care about different things.' },
      { title: 'Seasonal work comes and goes', body: 'Spring cleanups, fall leaf removal and snow plowing each have a short window, and the site rarely keeps up.' },
      { title: 'It is unclear where you work', body: 'Many landscapers cover a set radius. If the site does not say which towns, local searches have little to go on, and people outside your area fill your inbox with requests you cannot take.' },
    ],
    pages: [
      { name: 'Home', why: 'A strong photo of your work, your towns, your main services and a quote button.' },
      { name: 'Gallery', why: 'Before and after photos of patios, planting and lawns, uploaded from your phone and resized for speed.' },
      { name: 'A page per service', why: 'Landscape design, lawn care, hardscaping, irrigation and seasonal cleanups each get their own page.' },
      { name: 'Service area', why: 'The towns you cover, listed on one plain page.' },
      { name: 'Blog', why: 'Seasonal posts, like when to aerate your lawn in your area, that answer questions people search for.' },
      { name: 'Contact', why: 'A quote request form that lands in your inbox, plus phone and hours.' },
    ],
    searches: [
      'landscapers near me',
      'lawn care service [your city]',
      'patio installation near me',
      'landscape design [your city]',
      'spring yard cleanup near me',
      'retaining wall contractor [your city]',
    ],
    seo: [
      { title: 'Marked up as a Landscaping Business', body: 'Your structured data uses the LandscapingBusiness type with your address, phone and hours, the details Google uses for local results.' },
      { title: 'Photos that load fast', body: 'Galleries can be heavy. Your uploads are resized automatically, and every page must pass a 95+ speed check before it goes live.' },
      { title: 'Service pages with their own focus', body: 'Lawn care and hardscaping pages each have a title and heading about that service, so they can match the right searches.' },
      { title: 'Seasonal posts', body: 'Short posts timed to the season, like when to seed a lawn in your climate, show Google the site is active and give people a reason to find you before the rush.' },
      { title: 'Photos with plain descriptions', body: 'Each gallery photo can carry a short, honest description of the job, which helps people using screen readers and helps image search understand what it shows.' },
    ],
    sofie: [
      'Add a gallery with these photos of the Oak Street patio',
      'Add a page about fall leaf removal',
      'Write a blog post on when to aerate your lawn in our area',
      'Add snow plowing to our services for the winter',
      'Put a spring cleanup banner on the home page',
    ],
    faq: [
      { q: 'How much does it cost?', a: 'A 7-day free trial, then $15 a month for the site, hosting, your own domain, speed checks and changes by Sofie. No setup fees, and you can cancel anytime.' },
      { q: 'Do I need design skills to make the gallery look good?', a: 'No. Upload your photos and ask Sofie to add them to a gallery. The layout is handled for you, and you check the draft before it goes live.' },
      { q: 'Can I change services with the seasons?', a: 'Yes. Ask Sofie to add snow removal in November or a spring cleanup banner in March. Each change is a draft you approve, and you can undo it.' },
      { q: 'Will a gallery slow my site down?', a: 'It should not. Photos are resized automatically, and every page must pass a 95+ speed check before it can go live. If a change would slow a page, it gets fixed first.' },
      { q: 'Can customers request a quote?', a: 'Yes, through the contact form. Requests land in your inbox with reply and call buttons.' },
      { q: 'Do I get a logo?', a: 'If you do not have one, Sofie can design a simple logo for you. You can also upload your own.' },
    ],
  },

  // ------------------------------------------------------ Cleaning companies
  {
    slug: 'cleaning-companies',
    type: 'cleaner',
    example: 'bright-and-tidy',
    plural: 'cleaning companies',
    title: 'Websites for Cleaning Companies | SaySites',
    description: 'A fast cleaning company website that explains your services, shows where you work and collects quote requests through a simple form. From $15 a month.',
    kicker: 'Websites for cleaning companies',
    h1: 'A cleaning website that makes it easy to say yes',
    lede: 'People letting a cleaner into their home want to know exactly what is included and who is coming. SaySites builds a fast site that answers those questions and makes asking for a quote simple.',
    problems: [
      { title: 'Trust comes before price', body: 'Customers are handing over their keys. They want to see who you are, whether you are insured and what other clients say.' },
      { title: 'What is included is unclear', body: 'Regular cleaning, deep cleaning and move-out cleaning mean different things to different people. Vague descriptions lead to fewer quote requests and more disappointed customers.' },
      { title: 'Homes and offices in the same place', body: 'If you do both residential and commercial cleaning, each customer needs to find their kind of service quickly.' },
      { title: 'Quote requests get lost', body: 'Messages scattered across texts, social apps and voicemail are easy to miss, and a slow reply often means the client has already booked someone else.' },
    ],
    pages: [
      { name: 'Home', why: 'Who you are, where you clean, your main services and a clear button to ask for a quote.' },
      { name: 'A page per service', why: 'Regular, deep, move-in and move-out, and office cleaning each get a page explaining what is included.' },
      { name: 'About', why: 'The people behind the business, with any insurance and background-check details you want to share.' },
      { name: 'Testimonials', why: 'Real reviews from clients, shown in their own section.' },
      { name: 'Contact', why: 'A quote form that lands in one inbox, with your phone and the areas you serve.' },
      { name: 'Areas we clean', why: 'The towns and neighborhoods you cover, on one plain page, so local searches have something clear to match and clients know straight away if you come to them.' },
    ],
    searches: [
      'house cleaning near me',
      'deep cleaning service [your city]',
      'move out cleaning near me',
      'office cleaning [your city]',
      'maid service near me',
      'Airbnb cleaning service [your city]',
    ],
    seo: [
      { title: 'Marked up as a cleaning service', body: 'Structured data uses the HousekeepingService type with your address, phone and hours, so search engines understand what you do and where.' },
      { title: 'Clear service pages', body: 'Each service page has its own title and heading, like "Move-Out Cleaning in [your city]", and explains what is included in words people search for.' },
      { title: 'Helpful checklists', body: 'Posts like a move-out cleaning checklist answer common questions honestly and give people a reason to find your site.' },
      { title: 'Fast and simple', body: 'Every page passes a 95+ speed check before it goes live, and the site is built from clean, lean code that search engines read easily.' },
    ],
    sofie: [
      'Add a page about move-out cleaning with a checklist of what we cover',
      'Add a section about our insurance and background checks',
      'Write a blog post on how often to deep clean a kitchen',
      'Add these reviews from clients to the home page',
      'Add office cleaning as a separate service',
    ],
    faq: [
      { q: 'What does SaySites cost for a cleaning company?', a: '$15 a month after a 7-day free trial, for your site, hosting, your own domain, speed checks and changes by Sofie.' },
      { q: 'Do I need to be technical?', a: 'No. You describe your business and SaySites builds the site. Afterwards you ask Sofie for changes, like adding a service or updating your areas, and approve each draft.' },
      { q: 'Can clients book a cleaning online?', a: 'There is no booking system. Clients can call you or send a quote request through your contact form, and those messages land in your SaySites inbox.' },
      { q: 'Can I list prices?', a: 'Yes, if you want to. Starting prices or what affects a quote can go on each service page. Keep them accurate and up to date.' },
      { q: 'How do I show I am trustworthy?', a: 'Real photos of your team, an About page, accurate insurance details and genuine client reviews in a testimonials section. SaySites never invents reviews or claims.' },
      { q: 'Can I use my own domain?', a: 'Yes. You get a free yourname.saysites.com address and can connect a domain you already own.' },
    ],
  },

  // ------------------------------------------------------- Auto repair shops
  {
    slug: 'auto-repair-shops',
    type: 'autorepair',
    example: 'harbor-auto',
    plural: 'auto repair shops',
    title: 'Websites for Auto Repair Shops | SaySites',
    description: 'A fast auto repair website with your hours, directions, a page per service and a contact form for quotes, set up for local search. Built for you, $15/month.',
    kicker: 'Websites for auto repair shops',
    h1: 'An auto repair website drivers can trust',
    lede: 'Drivers pick a shop on trust, location and hours, often from a phone in a parking lot. SaySites builds a fast site that shows all three and gives each repair its own page.',
    problems: [
      { title: 'Drivers are wary of garages', body: 'People worry about being overcharged. A site that explains your work in plain language and shows real reviews goes a long way.' },
      { title: 'Hours and location decide the visit', body: 'If a driver cannot quickly see whether you are open and how to get there, they try the next shop.' },
      { title: 'Every repair is a separate search', body: 'Brakes, check engine lights, oil changes and transmissions are searched separately. A single list of services ranks for none of them.' },
      { title: 'Makes and specialties are hidden', body: 'If you specialize in certain makes, diesel or hybrids, customers looking for that need to see it. Otherwise they assume you are like every other garage and keep scrolling.' },
    ],
    pages: [
      { name: 'Home', why: 'Your hours, address, phone and main services right at the top, for drivers deciding where to go.' },
      { name: 'A page per service', why: 'Brake repair, check engine diagnostics, oil changes, tires and alignment each get their own page.' },
      { name: 'Makes we service', why: 'A section or page listing the makes and vehicle types you specialize in.' },
      { name: 'Testimonials', why: 'Real customer reviews that speak to honesty and fair pricing.' },
      { name: 'Contact and directions', why: 'Address, hours, phone and a form for repair questions. Messages land in your inbox.' },
      { name: 'Blog', why: 'Plain answers to common questions, like what a grinding noise when braking means.' },
    ],
    searches: [
      'auto repair near me',
      'brake repair [your city]',
      'check engine light diagnostic near me',
      'mechanic open Saturday near me',
      'honest mechanic [your city]',
      'Subaru repair shop near me',
    ],
    seo: [
      { title: 'Marked up as an Auto Repair shop', body: 'Structured data uses the AutoRepair type with your address, phone and opening hours, which Google uses for local results and to show whether you are open.' },
      { title: 'A page for each repair', body: 'Brakes, diagnostics and tires each get a page with its own title and heading, so each can match the searches drivers make.' },
      { title: 'Your hours kept current', body: 'Opening hours live in your business details and in the structured data. Ask Sofie when they change and both update together.' },
      { title: 'Plain answers, fast pages', body: 'Posts answering common car questions are useful to drivers, and every page passes a 95+ speed check before it goes live.' },
    ],
    sofie: [
      'Add a page about brake repair',
      'Change our Saturday hours to 8 to 1',
      'Add a section listing the makes we specialize in',
      'Write a blog post on what a check engine light can mean',
      'Add these reviews from customers to the home page',
    ],
    faq: [
      { q: 'How much does an auto repair website cost?', a: 'A 7-day free trial, then $15 a month for the site, hosting, your own domain, speed checks and changes by Sofie. No setup fees.' },
      { q: 'Do I need to know how websites work?', a: 'No. SaySites builds the site from a short description. You then ask Sofie for changes in plain words, check the draft and publish it, or undo it.' },
      { q: 'Can customers book an appointment online?', a: 'There is no booking system. Customers can call you or send a message through the contact form, which lands in your inbox with reply and call buttons.' },
      { q: 'Should I list prices?', a: 'It is your choice. Some shops list starting prices for common jobs like oil changes. If you do, keep them accurate so the site stays trustworthy.' },
      { q: 'Can I show which makes I work on?', a: 'Yes. Ask Sofie to add a section or page listing the makes and vehicle types you service. Only list the ones you actually handle.' },
      { q: 'Will Google show my hours?', a: 'Your hours are included in the structured data on your site. Google also uses your Google Business Profile, so keep your hours the same in both places.' },
    ],
  },

  // ---------------------------------------------------------------- Dentists
  {
    slug: 'dentists',
    type: 'dentist',
    example: 'willow-dental',
    plural: 'dentists',
    title: 'Websites for Dentists | SaySites',
    description: 'A calm, fast dental practice website that answers new-patient and insurance questions, with a page per treatment and a request form. From $15 a month.',
    kicker: 'Websites for dentists',
    h1: 'A dental website that puts new patients at ease',
    lede: 'People choosing a dentist want to know if you take their insurance, whether you are accepting new patients and what a first visit is like. SaySites builds a calm, fast site that answers those questions clearly.',
    problems: [
      { title: 'Insurance questions go unanswered', body: 'The first thing many patients check is whether you accept their plan. If the site does not say, they call someone whose site does.' },
      { title: 'Nervous patients need reassurance', body: 'Many people put off the dentist out of worry. A cold, clinical site does little to help them take the first step.' },
      { title: 'Treatments are searched one by one', body: 'Implants, Invisalign, whitening and emergency visits are separate searches, and a single services list does not rank for them.' },
      { title: 'Changes take weeks', body: 'Updating hours, adding a new dentist or changing the insurance list often means waiting on an agency.' },
    ],
    pages: [
      { name: 'Home', why: 'Who you are, where you are, your hours and a clear note on whether you are accepting new patients.' },
      { name: 'New patients', why: 'What to expect at a first visit, what to bring, and how to send a request through the form.' },
      { name: 'A page per treatment', why: 'Cleanings, implants, clear aligners, whitening and emergency care each get a page of their own.' },
      { name: 'Insurance and payment', why: 'The plans you accept and your payment options, kept current with a quick request to Sofie.' },
      { name: 'Meet the team', why: 'Photos and short bios of your dentists and hygienists, which help nervous patients feel they know you.' },
      { name: 'Contact', why: 'Phone, hours, address and an appointment request form that lands in your inbox.' },
    ],
    searches: [
      'dentist near me accepting new patients',
      'emergency dentist [your city]',
      'dentist that takes Delta Dental near me',
      'teeth whitening [your city]',
      'dental implants near me',
      'family dentist [your city]',
    ],
    seo: [
      { title: 'Marked up as a Dentist', body: 'Structured data describes your practice as a Dentist with your address, phone and opening hours, which is what Google uses for local results.' },
      { title: 'A page per treatment', body: 'Implants, aligners and emergency care each get their own page, title and heading, so each can match the searches patients make.' },
      { title: 'Answers to real patient questions', body: 'Clear pages on insurance and new patients, plus a questions section, answer what people search for in plain words.' },
      { title: 'Calm, fast pages', body: 'Every page passes a 95+ speed check before it goes live, and the design stays clean and easy to read on a phone.' },
    ],
    sofie: [
      'Add a page about dental implants',
      'Update our insurance list to add Cigna',
      'Add a new patients page explaining what happens at the first visit',
      'Add Dr. Patel to the team page with this photo',
      'Write a blog post on what to do if you chip a tooth',
    ],
    faq: [
      { q: 'What does a dental website cost with SaySites?', a: '$15 a month after a 7-day free trial, for the site, hosting, your own domain, speed checks and changes by Sofie. There are no setup fees.' },
      { q: 'Does anyone on my team need to be technical?', a: 'No. Anyone on your team can ask Sofie for changes in plain words, like updating the insurance list. Every change appears as a draft you check first, and you can undo it.' },
      { q: 'Can patients book appointments online?', a: 'There is no online booking system. Patients can call the practice or send an appointment request through the contact form, which lands in your inbox for your front desk to follow up.' },
      { q: 'Should I say which insurance we accept?', a: 'Yes, if you can keep it accurate. It is one of the most common questions patients have, and a clear insurance page saves your front desk calls.' },
      { q: 'Is the contact form suitable for medical details?', a: 'Keep it to appointment requests and contact details. Ask patients not to send medical or insurance ID information through the form, and handle those conversations through your usual channels.' },
      { q: 'Can I add before and after photos?', a: 'Yes, in a gallery, as long as you have the patient’s permission and the photos are real results from your practice.' },
    ],
  },

  // ------------------------------------------------------------- Hair salons
  {
    slug: 'hair-salons',
    type: 'salon',
    example: 'salt-and-stone',
    plural: 'hair salons',
    title: 'Websites for Hair Salons | SaySites',
    description: 'A fast, beautiful salon website with a gallery of your work, services and prices, your stylists and a request form, set up for local search. From $15 a month.',
    kicker: 'Websites for hair salons',
    h1: 'A salon website as polished as your work',
    lede: 'Clients choose a salon by looking at the work. SaySites builds a fast, elegant site with a gallery of your cuts and color, your services and prices, and an easy way to get in touch.',
    problems: [
      { title: 'Your portfolio lives on Instagram', body: 'Instagram is great for followers, but people searching for a colorist in your town on Google often never see it. Your own site with a gallery can be found there too.' },
      { title: 'Prices and services are unclear', body: 'People want to know roughly what a balayage or a cut will cost before they get in touch. Hiding it leads to fewer enquiries.' },
      { title: 'Clients choose a stylist, not only a salon', body: 'Many people are looking for a particular specialty, like curly hair or blonding, and want to know which stylist to ask for.' },
      { title: 'The site looks nothing like the salon', body: 'A generic template makes a carefully designed salon feel ordinary.' },
    ],
    pages: [
      { name: 'Home', why: 'A striking photo of your work, your location, your hours and a clear way to call or send a request.' },
      { name: 'Gallery', why: 'Cuts, color and styling from your own chairs, uploaded from your phone and resized so the site stays fast.' },
      { name: 'Services and prices', why: 'Cuts, color, balayage, treatments and styling with starting prices, so clients know what to expect.' },
      { name: 'Our stylists', why: 'Each stylist’s photo, specialties and experience, so clients can ask for the right person.' },
      { name: 'Testimonials', why: 'Real words from real clients.' },
      { name: 'Contact', why: 'Address, hours, phone and a request form that lands in your inbox.' },
    ],
    searches: [
      'hair salon near me',
      'balayage [your city]',
      'curly hair specialist near me',
      'best hair colorist [your city]',
      'men’s haircut near me',
      'bridal hair [your city]',
    ],
    seo: [
      { title: 'Marked up as a Hair Salon', body: 'Structured data uses the HairSalon type with your address, phone and opening hours, which Google uses for local results.' },
      { title: 'Pages for your specialties', body: 'If you are known for balayage or curly cuts, a page for each, with its own title and heading, can match the searches people make for them.' },
      { title: 'A gallery that stays fast', body: 'Photos are resized automatically and every page passes a 95+ speed check before it goes live, so a full gallery does not slow the site down.' },
      { title: 'Real work, real reviews', body: 'Your own photos and genuine client reviews build trust with visitors, and Google’s guidelines reward original content over stock images.' },
    ],
    sofie: [
      'Add these photos of balayage work to the gallery',
      'Add a page about our curly hair cuts',
      'Update the price for a full head of highlights',
      'Add Maya to the stylists page with her specialties',
      'Change our Thursday hours to 10 to 8',
    ],
    faq: [
      { q: 'How much does a salon website cost?', a: 'A 7-day free trial, then $15 a month for your site, hosting, your own domain, speed checks and changes by Sofie. No setup fees, cancel anytime.' },
      { q: 'I am not techy. Can I still run it?', a: 'Yes. You ask Sofie for changes in plain words, like adding photos or updating a price. You see each change as a draft and can undo anything.' },
      { q: 'Can clients book appointments online?', a: 'There is no booking system in SaySites. Clients can call the salon or send a request through the contact form. If you already use a separate booking service, Sofie can add a button that links to it.' },
      { q: 'Should my gallery just link to Instagram?', a: 'Keep Instagram, but put your best work on your own site too. Photos on your site can be found through Google, and they support the searches people make for your specialties.' },
      { q: 'Can I show prices?', a: 'Yes. A services and prices page is one of the most useful pages a salon can have. Starting prices are fine, and Sofie can update them whenever you ask.' },
      { q: 'Will it look like my salon?', a: 'You choose from calm, elegant designs, and Sofie can adjust colors, fonts and photos to match your space. If you need a logo, Sofie can design one.' },
    ],
  },

  // -------------------------------------------------------------- Restaurants
  {
    slug: 'restaurants',
    type: 'restaurant',
    example: 'olive-and-ember',
    plural: 'restaurants',
    title: 'Websites for Restaurants | SaySites',
    description: 'A fast restaurant website with your menu as a real web page, your hours, directions and photos, set up for local search and easy to update. From $15 a month.',
    kicker: 'Websites for restaurants',
    h1: 'A restaurant website with the menu people are looking for',
    lede: 'Most people visit a restaurant website for three things: the menu, the hours and where you are. SaySites builds a fast site that shows all three clearly and lets you update them by asking.',
    problems: [
      { title: 'The menu is a PDF or a photo', body: 'A PDF menu is slow on a phone, hard to read and hard for search engines to understand. A menu written as a real page loads fast and can be found.' },
      { title: 'Hours are out of date', body: 'Holiday closures and seasonal hours change often. A site with the wrong hours sends people to a locked door.' },
      { title: 'The site is slow on a phone', body: 'Diners decide where to eat on their phones, often while already out. Heavy photos and slow pages lose them.' },
      { title: 'Specials never make it online', body: 'The new seasonal menu or the Tuesday special is on the chalkboard but not on the website.' },
    ],
    pages: [
      { name: 'Home', why: 'A photo of your food, your hours, address and phone, so a hungry visitor can decide in seconds.' },
      { name: 'Menu', why: 'Your menu as a real web page, with dishes and prices as text, easy to read on a phone and easy to update.' },
      { name: 'About', why: 'Your story, your kitchen and what makes you different.' },
      { name: 'Gallery', why: 'Photos of your dishes and dining room, resized automatically for speed.' },
      { name: 'Private events', why: 'If you host parties, a page explaining what you offer, with enquiries through the contact form.' },
      { name: 'Contact and hours', why: 'Address, hours, phone and a form for questions and event enquiries.' },
    ],
    searches: [
      'Italian restaurant near me',
      '[restaurant name] menu',
      'restaurants open now near me',
      'best brunch [your city]',
      'private dining room [your city]',
      'gluten free restaurant near me',
    ],
    seo: [
      { title: 'Marked up as a Restaurant', body: 'Structured data uses the Restaurant type with your address, phone and opening hours, the details Google shows when people search for places to eat.' },
      { title: 'A menu Google can read', body: 'Your menu is written as text on its own page, with a clear title like "Menu | [your restaurant]", instead of an image or PDF search engines cannot read well.' },
      { title: 'Hours that stay right', body: 'Opening hours sit in your business details and structured data. Tell Sofie about a holiday change and it updates in one place.' },
      { title: 'Fast pages full of food photos', body: 'Photos are resized automatically and every page passes a 95+ speed check, so the site stays quick for people deciding where to eat right now.' },
    ],
    sofie: [
      'Update the menu with our new fall dishes',
      'We are closed on Thanksgiving, add that to the site',
      'Add a private events page',
      'Mark the vegetarian and gluten-free dishes on the menu',
      'Add these photos of the new patio to the gallery',
    ],
    faq: [
      { q: 'How much does a restaurant website cost?', a: '$15 a month after a 7-day free trial, for your site, hosting, your own domain, speed checks and changes by Sofie.' },
      { q: 'Do I need to be technical to update the menu?', a: 'No. Tell Sofie what changed, like a new dish or a new price, and she updates the menu page. You see the draft first and can undo it.' },
      { q: 'Can people order food or reserve a table online?', a: 'SaySites does not take food orders or reservations. Guests can call you or send a message through your contact form. If you already use a separate ordering or reservation service, Sofie can add a button that links to it.' },
      { q: 'Why not just upload my PDF menu?', a: 'A PDF is slow and awkward on a phone and harder for search engines to understand. A menu written as a page is quicker to read, easier to update and can show up for searches about your dishes.' },
      { q: 'Can I note allergens and dietary options?', a: 'Yes. Sofie can mark vegetarian, vegan or gluten-free dishes on the menu. Only mark what is accurate, and keep a note inviting guests to ask about allergies.' },
      { q: 'What is the weekly standing?', a: 'Each week you get a private standing showing how your site compares with similar businesses on SaySites, along with steps that would help you move up.' },
    ],
  },

  // ------------------------------------------------------- Bakeries and cafés
  {
    slug: 'bakeries-and-cafes',
    type: 'bakery',
    example: 'rosies-bakery',
    plural: 'bakeries and cafés',
    title: 'Websites for Bakeries and Cafés | SaySites',
    description: 'A warm, fast website for your bakery or café with your hours, what is baked today, photos and a contact form for cake orders. Set up for local search.',
    kicker: 'Websites for bakeries and cafés',
    h1: 'A bakery and café website as warm as the shop',
    lede: 'People looking for coffee or fresh bread want to know one thing first: are you open right now. SaySites builds a warm, fast site that answers that and shows off what you bake.',
    problems: [
      { title: '"Open now" decides the visit', body: 'Café searches are often made on the spot. If your hours are missing or wrong, people walk to the place that shows them clearly.' },
      { title: 'The good stuff is not online', body: 'Your pastry case changes daily, but the website shows the same three photos from opening day.' },
      { title: 'Custom orders come in by every route', body: 'Cake and catering requests arrive by phone, text and social messages, and details get lost.' },
      { title: 'Social media is not a website', body: 'Posts disappear into the feed. Someone searching Google for sourdough in your town needs a page that stays put.' },
    ],
    pages: [
      { name: 'Home', why: 'Your hours, address and a photo that makes people hungry, right at the top.' },
      { name: 'Menu', why: 'Breads, pastries, cakes and drinks written as text, with prices if you like, easy to update when things change.' },
      { name: 'Cakes and custom orders', why: 'What you make to order, how much notice you need, and a form to send a request.' },
      { name: 'Gallery', why: 'Photos of your bakes and your space, resized automatically so the site stays fast.' },
      { name: 'Visit', why: 'Address, hours, parking and seating, so people know what to expect.' },
      { name: 'Blog', why: 'Seasonal specials and news, like when hot cross buns are back.' },
    ],
    searches: [
      'bakery near me',
      'coffee shop open now near me',
      'custom birthday cake [your city]',
      'sourdough bread near me',
      'café with wifi [your city]',
      'gluten free bakery near me',
    ],
    seo: [
      { title: 'Marked up as a Bakery', body: 'Structured data uses the Bakery type with your address, phone and opening hours, which is what powers "open now" style results.' },
      { title: 'Hours kept accurate', body: 'Your hours live in your business details. Tell Sofie about a holiday closure and the site and its structured data update together.' },
      { title: 'A menu page with real text', body: 'Breads, pastries and drinks written as text give search engines something to match against searches like "sourdough near me".' },
      { title: 'Fresh posts for seasonal favorites', body: 'Short posts about seasonal bakes show that the business is active and give regulars a reason to check back.' },
    ],
    sofie: [
      'Add pumpkin loaf and apple hand pies to the menu',
      'We are closing at 2 on Christmas Eve, add that to the site',
      'Add a custom cakes page with a request form',
      'Write a short post that our hot cross buns are back',
      'Add these photos of this morning’s bakes to the gallery',
    ],
    faq: [
      { q: 'What does a bakery website cost?', a: 'After a 7-day free trial, $15 a month for a site, or $25 a month for a Store if you want to sell packaged goods through your own Stripe account. SaySites takes 0% of sales.' },
      { q: 'Do I need to know anything about websites?', a: 'No. You describe your bakery and SaySites builds the site. Then you ask Sofie for changes in plain words and check each draft before it goes live.' },
      { q: 'Can customers order cakes online?', a: 'They can send a cake request through your contact form with the details, and it lands in your inbox. There is no online ordering or pickup system for daily bakes.' },
      { q: 'How do I show when we are open?', a: 'Add your opening hours once and they appear on the site and in its structured data. Keep them the same on your Google Business Profile.' },
      { q: 'Can I sell things online?', a: 'Yes, on the Store plan. You can add products such as bags of coffee or gift boxes, and customers pay you through your own Stripe account, with nothing taken by SaySites.' },
      { q: 'I post on Instagram every day. Do I still need a site?', a: 'Instagram is great for regulars. A website is what people find on Google when they search for a bakery or café near them, and it holds your hours, menu and address in one place.' },
    ],
  },

  // -------------------------------------------------------------------- Shops
  {
    slug: 'shops',
    type: 'store',
    example: 'field-and-thread',
    plural: 'independent shops',
    title: 'Websites for Independent Shops | SaySites',
    description: 'A fast website for your independent shop with products, a Shop page, your hours and directions. Customers pay through your own Stripe, 0% taken.',
    kicker: 'Websites for independent shops',
    h1: 'A website for your shop, and a shop on your website',
    lede: 'Independent shops need people to find the store and, often, to buy online too. SaySites builds a fast site with your hours and location, plus a Shop page where customers pay you through your own Stripe account.',
    problems: [
      { title: 'Marketplaces take a cut', body: 'Selling through big platforms means fees on every sale and customers who remember the platform, not your shop.' },
      { title: 'Locals do not know what you stock', body: 'People search for a specific kind of thing nearby. If your site does not say what you carry, they never find out you have it.' },
      { title: 'Two websites to run', body: 'Many shops end up with one site for the store and another for selling online, and neither is kept up.' },
      { title: 'Opening hours and events get missed', body: 'Late openings, markets and holiday hours change often, and an outdated site costs visits. In the busy season, a wrong closing time can mean a customer who does not come back.' },
    ],
    pages: [
      { name: 'Home', why: 'What you sell, where you are and your hours, with a few featured products.' },
      { name: 'Shop', why: 'Your products with prices and photos. Customers pay through your own Stripe account, and SaySites takes 0%.' },
      { name: 'Collections or categories', why: 'Pages for what you stock, like homewares or local makers, so people searching for them can find you.' },
      { name: 'About', why: 'Your story, the makers you work with and what makes your shop worth the trip.' },
      { name: 'Visit', why: 'Address, hours, parking and directions for people coming in person.' },
      { name: 'Contact', why: 'A form for questions and special requests that lands in your inbox.' },
    ],
    searches: [
      'gift shop near me',
      'independent bookstore [your city]',
      'locally made gifts [your city]',
      'yarn store near me',
      'home decor shop [your city]',
      'where to buy [product] near me',
    ],
    seo: [
      { title: 'Marked up as a Store', body: 'Structured data describes your business as a Store with your address, phone and opening hours, for people searching for shops nearby.' },
      { title: 'Prices Google can read', body: 'Products on your Shop page include their prices in a form search engines understand.' },
      { title: 'Pages for what you stock', body: 'Collection pages with their own titles and headings help you match searches for the kinds of things you carry.' },
      { title: 'Fast, even with lots of photos', body: 'Product photos are resized automatically, and every page passes a 95+ speed check before it goes live.' },
    ],
    sofie: [
      'Add these five new candles to the shop',
      'Add a page for our local makers collection',
      'We are open late on Thursdays in December, add that to the site',
      'Put our holiday gift guide on the home page',
      'Write a blog post about the makers we stock this season',
    ],
    faq: [
      { q: 'How much does it cost to sell online?', a: 'The Store plan is $25 a month, after a 7-day free trial. Customers pay you through your own Stripe account. Stripe charges its normal card fee, and SaySites takes nothing on top.' },
      { q: 'Do I need to be technical to add products?', a: 'No. Ask Sofie to add products with their names, prices and photos. You see the change as a draft first and can undo it.' },
      { q: 'What if I only want a site for the shop, not online sales?', a: 'Then the Site plan at $15 a month is enough. It covers your pages, hours, location, blog and contact form. You can add a Store later.' },
      { q: 'Will my products show up on Google?', a: 'Your product pages include prices in a form Google can read, and the site is fast and cleanly built. No one can promise rankings, but the foundations are set up properly.' },
      { q: 'Can I use my own domain?', a: 'Yes. Every site gets a free yourname.saysites.com address, and you can connect a domain you already own.' },
      { q: 'How do I know if the site is working?', a: 'Your dashboard shows visitors per day and your most-read pages, counted without cookies. Your Visibility Score shows how findable the site is, with steps to improve it.' },
    ],
  },
]
