import { describe, it, expect } from 'vitest'
import { classifyWordPressError } from '../errors'

describe('classifyWordPressError', () => {
  it('classifies a SiteGround sgcaptcha challenge page as proxy_challenge, even on an unusual HTTP 202', () => {
    // Regression: found via live testing against a real SiteGround-hosted
    // WordPress site (envuetelematics.com). SiteGround's hosting-level bot
    // protection intercepted the /wp-json/ request before WordPress ever
    // saw it, returning a meta-refresh redirect to /.well-known/sgcaptcha/
    // on HTTP 202 — not one of the status codes (403/503) the classifier
    // previously checked for challenge pages, so it fell back to a
    // misleading "domain may be down" message despite the domain clearly
    // being reachable (steps 1-3 already succeeded).
    const r = classifyWordPressError({
      httpStatus: 202,
      bodyText: '<html><head><link rel="icon" href="data:;"><meta http-equiv="refresh" content="0;/.well-known/sgcaptcha/?r=%2Fwp-json%2F&y=ipc:3.88.159.235:1784224861.883"></head></html>',
      step: 'rest discovery',
    })
    expect(r.category).toBe('proxy_challenge')
    expect(r.category).not.toBe('site_unreachable')
    expect(r.whatToDo.toLowerCase()).toContain('security')
  })

  it('classifies 401 with password wording as invalid_app_password', () => {
    const r = classifyWordPressError({ httpStatus: 401, bodyText: '{"code":"incorrect_password","message":"Incorrect password."}' })
    expect(r.category).toBe('invalid_app_password')
    expect(r.canRetry).toBe(true)
  })

  it('classifies 401 with username wording as invalid_username', () => {
    const r = classifyWordPressError({ httpStatus: 401, bodyText: '{"code":"invalid_username","message":"Unknown username."}' })
    expect(r.category).toBe('invalid_username')
  })

  it('classifies a rest_not_logged_in 401 as authorization_header_not_forwarded, not invalid_app_password', () => {
    // Regression: found via live testing against a real WordPress site
    // (envuetelematics.com). WordPress's generic "no auth method recognized"
    // fallback was being misdiagnosed as a wrong password, sending the user
    // to regenerate credentials that were never actually checked — a fresh
    // admin account + fresh Application Password reproduced the identical
    // error, which only makes sense if the Authorization header itself never
    // reached WordPress (a common FastCGI/PHP-FPM hosting configuration gap).
    const r = classifyWordPressError({
      httpStatus: 401,
      bodyText: '{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}',
      step: 'authentication',
    })
    expect(r.category).toBe('authorization_header_not_forwarded')
    expect(r.category).not.toBe('invalid_app_password')
    expect(r.whatToDo).toContain('Authorization')
    expect(r.canRetry).toBe(true)
  })

  it('classifies 403 with Wordfence signature as security_plugin_blocking', () => {
    const r = classifyWordPressError({ httpStatus: 403, bodyText: '<html>Generated by Wordfence</html>' })
    expect(r.category).toBe('security_plugin_blocking')
  })

  it('classifies 403 with cf-ray header as proxy_challenge', () => {
    const r = classifyWordPressError({ httpStatus: 403, bodyText: '', headers: { 'cf-ray': 'abc123' } })
    expect(r.category).toBe('proxy_challenge')
  })

  it('classifies 403 with capability wording as insufficient_permissions during a post-auth capability check', () => {
    const r = classifyWordPressError({ httpStatus: 403, bodyText: '{"code":"rest_forbidden","message":"Sorry, you are not allowed to edit_posts."}', step: 'edit permission' })
    expect(r.category).toBe('insufficient_permissions')
  })

  it('does not claim "insufficient permissions" for a 403 before any identity has been established', () => {
    // Regression: a non-WordPress host returning a bare 403 to the initial,
    // unauthenticated /wp-json/ reachability check was previously
    // misclassified as "your account lacks edit permission" — nonsensical
    // before any account has even been verified. Found via live E2E testing
    // against a real (non-WordPress) host.
    const r = classifyWordPressError({ httpStatus: 403, bodyText: '', step: 'wp-json reachability' })
    expect(r.category).not.toBe('insufficient_permissions')
    expect(r.category).toBe('hosting_firewall_blocking')
  })

  it('classifies a network exception with no status as site_unreachable', () => {
    const r = classifyWordPressError({ exceptionName: 'TypeError', exceptionMessage: 'fetch failed' })
    expect(r.category).toBe('site_unreachable')
  })

  it('classifies an AbortError as server_timeout', () => {
    const r = classifyWordPressError({ exceptionName: 'AbortError', exceptionMessage: 'The operation was aborted.' })
    expect(r.category).toBe('server_timeout')
  })

  it('classifies a certificate exception as ssl_certificate_error', () => {
    const r = classifyWordPressError({ exceptionMessage: 'unable to verify the first certificate' })
    expect(r.category).toBe('ssl_certificate_error')
  })

  it('classifies a redirect-loop message as redirect_loop', () => {
    const r = classifyWordPressError({ exceptionMessage: 'Too many redirects — possible redirect loop.' })
    expect(r.category).toBe('redirect_loop')
  })

  it('includes request URL, method, and response headers in technical details when provided', () => {
    // These fields are what a hosting provider's support team needs to
    // locate a specific request in their own logs — added after a live
    // support escalation (SiteGround) asked for exact URL, method, and
    // response headers alongside status/body, none of which were being
    // captured before this.
    const r = classifyWordPressError({
      httpStatus: 202,
      bodyText: '<html>challenge page</html>',
      headers: { 'content-type': 'text/html', 'x-example-header': 'value123' },
      step: 'rest discovery',
      requestUrl: 'https://example.com/wp-json/',
      requestMethod: 'GET',
    })
    expect(r.technicalDetails).toContain('GET https://example.com/wp-json/')
    expect(r.technicalDetails).toContain('content-type: text/html')
    expect(r.technicalDetails).toContain('x-example-header: value123')
  })

  it('classifies an SSRF block message as rankforge_configuration_error and is not retryable', () => {
    const r = classifyWordPressError({ exceptionMessage: 'Blocked outbound URL: Private / reserved IP addresses are not allowed.' })
    expect(r.category).toBe('rankforge_configuration_error')
    expect(r.canRetry).toBe(false)
  })

  it('falls back to unknown for an unrecognized status', () => {
    const r = classifyWordPressError({ httpStatus: 418 })
    expect(r.category).toBe('unknown')
  })

  it('every category includes actionable copy', () => {
    const r = classifyWordPressError({ httpStatus: 401 })
    expect(r.whatFailed.length).toBeGreaterThan(0)
    expect(r.whyLikely.length).toBeGreaterThan(0)
    expect(r.whatToDo.length).toBeGreaterThan(0)
    expect(typeof r.canRetry).toBe('boolean')
  })

  it('never leaks a credential in technical details', () => {
    const r = classifyWordPressError({
      httpStatus: 401,
      bodyText: 'Authorization: Basic dXNlcjpzdXBlcnNlY3JldHBhc3M=',
    })
    expect(r.technicalDetails).not.toContain('dXNlcjpzdXBlcnNlY3JldHBhc3M=')
    expect(r.technicalDetails).toContain('[redacted]')
  })
})
