import type { AiInsights, ScoreEntry } from '@/lib/types'
import { ScoreBadge } from '@/components/ScoreBadge'

export function AiSearchSection({ ai, aiScore }: { ai: AiInsights | null; aiScore: ScoreEntry | null }) {
  if (!ai) return null
  return (
    <section className="card">
      <div className="mb-1 flex items-center justify-between gap-3">
        <h2 className="section-title !mb-0">AI search / GEO / AEO optimization</h2>
        {aiScore && (
          <div className="flex items-center gap-2 text-sm text-slate-500">
            AI readiness <ScoreBadge score={aiScore.score} />
          </div>
        )}
      </div>
      <p className="section-subtitle">
        {aiScore?.explanation ?? 'Optimizing for AI Overviews, featured snippets and LLM-powered search.'}
        {ai.generatedBy
          ? ` Suggestions generated by ${ai.generatedBy} from the extracted data.`
          : ' Suggestions are rule-generated from the extracted data (no AI key configured).'}
      </p>

      {ai.shortAnswerBlock && (
        <div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4">
          <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-emerald-700">
            Suggested short-answer block (place directly under your H1)
          </p>
          <p className="text-sm leading-relaxed text-emerald-900">{ai.shortAnswerBlock}</p>
        </div>
      )}

      <div className="grid gap-6 md:grid-cols-2">
        {ai.aiSearchRecommendations.length > 0 && (
          <div>
            <h3 className="mb-2 text-sm font-semibold text-slate-800">AI Overview & answer-engine recommendations</h3>
            <ul className="space-y-2">
              {ai.aiSearchRecommendations.map((r, i) => (
                <li key={i} className="rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700">{r}</li>
              ))}
            </ul>
          </div>
        )}
        {ai.faqSuggestions.length > 0 && (
          <div>
            <h3 className="mb-2 text-sm font-semibold text-slate-800">FAQ questions to add</h3>
            <ul className="space-y-2">
              {ai.faqSuggestions.map((q, i) => (
                <li key={i} className="rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700">{q}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </section>
  )
}
